# Generated by Django 3.0.5 on 2020-05-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('excerpt', models.TextField(max_length=300)),
                ('viewer', models.PositiveIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='Blog_picture')),
            ],
        ),
    ]
